get http://localhost:3000/users

###
post http://localhost:3000/users
Content-Type: application/json

{
    "name": [ENTER NAME],
    "email": [ENTER EMAIL]
}

###
PUT http://localhost:3000/users/5
Content-Type: application/json

{
    "name": [ENTER NAME],
    "email": [ENTER EMAIL]
}

###
DELETE http://localhost:3000/users/5
