get http://localhost:3000/users

###
post http://localhost:3000/users
Content-Type: application/json

{
    "name": "Kevin",
    "email": "kevin@example.com"
}

###
PUT http://localhost:3000/users/5
Content-Type: application/json

{
    "name": "Chris",
    "email": "Robinson"
}